### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by oybek94** [IqboljonAbdumalikov/Insure-Landing-Page#2]
Need to be fixed

https://github.com/IqboljonAbdumalikov/Insure-Landing-Page/blob/22e2f77fa8aa40cb5eec837b3d5e3fb303d25c4f/css/styles.css#L39

**Comment by IqboljonAbdumalikov** [comment]
Muammo yechildi. Men padding ni linkga emas, itemga berib yuboribman va hover paytida faqat linkni ustiga borganda o'zgarayotgan ekan.
